// flow-typed signature: 21c16302e2956061e63c6b2faf15230d
// flow-typed version: <<STUB>>/animejs_v^3.2.1/flow_v0.156.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animejs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animejs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'animejs/lib/anime.es' {
  declare module.exports: any;
}

declare module 'animejs/lib/anime' {
  declare module.exports: any;
}

declare module 'animejs/lib/anime.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'animejs/lib/anime.es.js' {
  declare module.exports: $Exports<'animejs/lib/anime.es'>;
}
declare module 'animejs/lib/anime.js' {
  declare module.exports: $Exports<'animejs/lib/anime'>;
}
declare module 'animejs/lib/anime.min.js' {
  declare module.exports: $Exports<'animejs/lib/anime.min'>;
}
