// flow-typed signature: 84546ba2df8d454105a60d55dab6a9b1
// flow-typed version: <<STUB>>/esinstall_v^1.1.7/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'esinstall'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'esinstall' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'esinstall/lib/entrypoints' {
  declare module.exports: any;
}

declare module 'esinstall/lib' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/generateProcessPolyfill' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/rollup-plugin-alias' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/rollup-plugin-catch-fetch' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/rollup-plugin-catch-unresolved' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/rollup-plugin-css' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/rollup-plugin-node-process-polyfill' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/rollup-plugin-stats' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/rollup-plugin-strip-source-mapping' {
  declare module.exports: any;
}

declare module 'esinstall/lib/rollup-plugins/rollup-plugin-wrap-install-targets' {
  declare module.exports: any;
}

declare module 'esinstall/lib/stats' {
  declare module.exports: any;
}

declare module 'esinstall/lib/types' {
  declare module.exports: any;
}

declare module 'esinstall/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'esinstall/lib/entrypoints.js' {
  declare module.exports: $Exports<'esinstall/lib/entrypoints'>;
}
declare module 'esinstall/lib/index' {
  declare module.exports: $Exports<'esinstall/lib'>;
}
declare module 'esinstall/lib/index.js' {
  declare module.exports: $Exports<'esinstall/lib'>;
}
declare module 'esinstall/lib/rollup-plugins/generateProcessPolyfill.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/generateProcessPolyfill'>;
}
declare module 'esinstall/lib/rollup-plugins/rollup-plugin-alias.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/rollup-plugin-alias'>;
}
declare module 'esinstall/lib/rollup-plugins/rollup-plugin-catch-fetch.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/rollup-plugin-catch-fetch'>;
}
declare module 'esinstall/lib/rollup-plugins/rollup-plugin-catch-unresolved.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/rollup-plugin-catch-unresolved'>;
}
declare module 'esinstall/lib/rollup-plugins/rollup-plugin-css.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/rollup-plugin-css'>;
}
declare module 'esinstall/lib/rollup-plugins/rollup-plugin-node-process-polyfill.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/rollup-plugin-node-process-polyfill'>;
}
declare module 'esinstall/lib/rollup-plugins/rollup-plugin-stats.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/rollup-plugin-stats'>;
}
declare module 'esinstall/lib/rollup-plugins/rollup-plugin-strip-source-mapping.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/rollup-plugin-strip-source-mapping'>;
}
declare module 'esinstall/lib/rollup-plugins/rollup-plugin-wrap-install-targets.js' {
  declare module.exports: $Exports<'esinstall/lib/rollup-plugins/rollup-plugin-wrap-install-targets'>;
}
declare module 'esinstall/lib/stats.js' {
  declare module.exports: $Exports<'esinstall/lib/stats'>;
}
declare module 'esinstall/lib/types.js' {
  declare module.exports: $Exports<'esinstall/lib/types'>;
}
declare module 'esinstall/lib/util.js' {
  declare module.exports: $Exports<'esinstall/lib/util'>;
}
