// flow-typed signature: fc01903a5c9ccb5322732a7c8f84a91a
// flow-typed version: <<STUB>>/finalhandler_v^1.1.2/flow_v0.156.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'finalhandler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'finalhandler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'finalhandler/index' {
  declare module.exports: $Exports<'finalhandler'>;
}
declare module 'finalhandler/index.js' {
  declare module.exports: $Exports<'finalhandler'>;
}
