// flow-typed signature: be17ba52d1c1e0d3fe2a5e3a315a66f3
// flow-typed version: <<STUB>>/htm_v^3.0.4/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'htm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'htm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'htm/dist/htm' {
  declare module.exports: any;
}

declare module 'htm/dist/htm.module' {
  declare module.exports: any;
}

declare module 'htm/dist/htm.umd' {
  declare module.exports: any;
}

declare module 'htm/mini' {
  declare module.exports: any;
}

declare module 'htm/mini/index.module' {
  declare module.exports: any;
}

declare module 'htm/mini/index.umd' {
  declare module.exports: any;
}

declare module 'htm/preact' {
  declare module.exports: any;
}

declare module 'htm/preact/index.module' {
  declare module.exports: any;
}

declare module 'htm/preact/index.umd' {
  declare module.exports: any;
}

declare module 'htm/preact/standalone.module' {
  declare module.exports: any;
}

declare module 'htm/preact/standalone.umd' {
  declare module.exports: any;
}

declare module 'htm/react' {
  declare module.exports: any;
}

declare module 'htm/react/index.module' {
  declare module.exports: any;
}

declare module 'htm/react/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'htm/dist/htm.js' {
  declare module.exports: $Exports<'htm/dist/htm'>;
}
declare module 'htm/dist/htm.module.js' {
  declare module.exports: $Exports<'htm/dist/htm.module'>;
}
declare module 'htm/dist/htm.umd.js' {
  declare module.exports: $Exports<'htm/dist/htm.umd'>;
}
declare module 'htm/mini/index' {
  declare module.exports: $Exports<'htm/mini'>;
}
declare module 'htm/mini/index.js' {
  declare module.exports: $Exports<'htm/mini'>;
}
declare module 'htm/mini/index.module.js' {
  declare module.exports: $Exports<'htm/mini/index.module'>;
}
declare module 'htm/mini/index.umd.js' {
  declare module.exports: $Exports<'htm/mini/index.umd'>;
}
declare module 'htm/preact/index' {
  declare module.exports: $Exports<'htm/preact'>;
}
declare module 'htm/preact/index.js' {
  declare module.exports: $Exports<'htm/preact'>;
}
declare module 'htm/preact/index.module.js' {
  declare module.exports: $Exports<'htm/preact/index.module'>;
}
declare module 'htm/preact/index.umd.js' {
  declare module.exports: $Exports<'htm/preact/index.umd'>;
}
declare module 'htm/preact/standalone.module.js' {
  declare module.exports: $Exports<'htm/preact/standalone.module'>;
}
declare module 'htm/preact/standalone.umd.js' {
  declare module.exports: $Exports<'htm/preact/standalone.umd'>;
}
declare module 'htm/react/index' {
  declare module.exports: $Exports<'htm/react'>;
}
declare module 'htm/react/index.js' {
  declare module.exports: $Exports<'htm/react'>;
}
declare module 'htm/react/index.module.js' {
  declare module.exports: $Exports<'htm/react/index.module'>;
}
declare module 'htm/react/index.umd.js' {
  declare module.exports: $Exports<'htm/react/index.umd'>;
}
