// flow-typed signature: ea8229f6b4b32276d0d5aaba3c219bdf
// flow-typed version: <<STUB>>/preact_v^10.4.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact/compat/dist/compat' {
  declare module.exports: any;
}

declare module 'preact/compat/dist/compat.module' {
  declare module.exports: any;
}

declare module 'preact/compat/dist/compat.umd' {
  declare module.exports: any;
}

declare module 'preact/compat/server' {
  declare module.exports: any;
}

declare module 'preact/compat/src/Children' {
  declare module.exports: any;
}

declare module 'preact/compat/src/events' {
  declare module.exports: any;
}

declare module 'preact/compat/src/forwardRef' {
  declare module.exports: any;
}

declare module 'preact/compat/src' {
  declare module.exports: any;
}

declare module 'preact/compat/src/memo' {
  declare module.exports: any;
}

declare module 'preact/compat/src/portals' {
  declare module.exports: any;
}

declare module 'preact/compat/src/PureComponent' {
  declare module.exports: any;
}

declare module 'preact/compat/src/render' {
  declare module.exports: any;
}

declare module 'preact/compat/src/suspense-list' {
  declare module.exports: any;
}

declare module 'preact/compat/src/suspense' {
  declare module.exports: any;
}

declare module 'preact/compat/src/util' {
  declare module.exports: any;
}

declare module 'preact/debug/dist/debug' {
  declare module.exports: any;
}

declare module 'preact/debug/dist/debug.module' {
  declare module.exports: any;
}

declare module 'preact/debug/dist/debug.umd' {
  declare module.exports: any;
}

declare module 'preact/debug/src/check-props' {
  declare module.exports: any;
}

declare module 'preact/debug/src/component-stack' {
  declare module.exports: any;
}

declare module 'preact/debug/src/constants' {
  declare module.exports: any;
}

declare module 'preact/debug/src/debug' {
  declare module.exports: any;
}

declare module 'preact/debug/src' {
  declare module.exports: any;
}

declare module 'preact/devtools/dist/devtools' {
  declare module.exports: any;
}

declare module 'preact/devtools/dist/devtools.module' {
  declare module.exports: any;
}

declare module 'preact/devtools/dist/devtools.umd' {
  declare module.exports: any;
}

declare module 'preact/devtools/src/devtools' {
  declare module.exports: any;
}

declare module 'preact/devtools/src' {
  declare module.exports: any;
}

declare module 'preact/dist/preact' {
  declare module.exports: any;
}

declare module 'preact/dist/preact.min' {
  declare module.exports: any;
}

declare module 'preact/dist/preact.module' {
  declare module.exports: any;
}

declare module 'preact/dist/preact.umd' {
  declare module.exports: any;
}

declare module 'preact/hooks/dist/hooks' {
  declare module.exports: any;
}

declare module 'preact/hooks/dist/hooks.module' {
  declare module.exports: any;
}

declare module 'preact/hooks/dist/hooks.umd' {
  declare module.exports: any;
}

declare module 'preact/hooks/src' {
  declare module.exports: any;
}

declare module 'preact/src/clone-element' {
  declare module.exports: any;
}

declare module 'preact/src/component' {
  declare module.exports: any;
}

declare module 'preact/src/constants' {
  declare module.exports: any;
}

declare module 'preact/src/create-context' {
  declare module.exports: any;
}

declare module 'preact/src/create-element' {
  declare module.exports: any;
}

declare module 'preact/src/diff/catch-error' {
  declare module.exports: any;
}

declare module 'preact/src/diff/children' {
  declare module.exports: any;
}

declare module 'preact/src/diff' {
  declare module.exports: any;
}

declare module 'preact/src/diff/props' {
  declare module.exports: any;
}

declare module 'preact/src' {
  declare module.exports: any;
}

declare module 'preact/src/options' {
  declare module.exports: any;
}

declare module 'preact/src/render' {
  declare module.exports: any;
}

declare module 'preact/src/util' {
  declare module.exports: any;
}

declare module 'preact/test-utils/dist/testUtils' {
  declare module.exports: any;
}

declare module 'preact/test-utils/dist/testUtils.module' {
  declare module.exports: any;
}

declare module 'preact/test-utils/dist/testUtils.umd' {
  declare module.exports: any;
}

declare module 'preact/test-utils/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact/compat/dist/compat.js' {
  declare module.exports: $Exports<'preact/compat/dist/compat'>;
}
declare module 'preact/compat/dist/compat.module.js' {
  declare module.exports: $Exports<'preact/compat/dist/compat.module'>;
}
declare module 'preact/compat/dist/compat.umd.js' {
  declare module.exports: $Exports<'preact/compat/dist/compat.umd'>;
}
declare module 'preact/compat/server.js' {
  declare module.exports: $Exports<'preact/compat/server'>;
}
declare module 'preact/compat/src/Children.js' {
  declare module.exports: $Exports<'preact/compat/src/Children'>;
}
declare module 'preact/compat/src/events.js' {
  declare module.exports: $Exports<'preact/compat/src/events'>;
}
declare module 'preact/compat/src/forwardRef.js' {
  declare module.exports: $Exports<'preact/compat/src/forwardRef'>;
}
declare module 'preact/compat/src/index' {
  declare module.exports: $Exports<'preact/compat/src'>;
}
declare module 'preact/compat/src/index.js' {
  declare module.exports: $Exports<'preact/compat/src'>;
}
declare module 'preact/compat/src/memo.js' {
  declare module.exports: $Exports<'preact/compat/src/memo'>;
}
declare module 'preact/compat/src/portals.js' {
  declare module.exports: $Exports<'preact/compat/src/portals'>;
}
declare module 'preact/compat/src/PureComponent.js' {
  declare module.exports: $Exports<'preact/compat/src/PureComponent'>;
}
declare module 'preact/compat/src/render.js' {
  declare module.exports: $Exports<'preact/compat/src/render'>;
}
declare module 'preact/compat/src/suspense-list.js' {
  declare module.exports: $Exports<'preact/compat/src/suspense-list'>;
}
declare module 'preact/compat/src/suspense.js' {
  declare module.exports: $Exports<'preact/compat/src/suspense'>;
}
declare module 'preact/compat/src/util.js' {
  declare module.exports: $Exports<'preact/compat/src/util'>;
}
declare module 'preact/debug/dist/debug.js' {
  declare module.exports: $Exports<'preact/debug/dist/debug'>;
}
declare module 'preact/debug/dist/debug.module.js' {
  declare module.exports: $Exports<'preact/debug/dist/debug.module'>;
}
declare module 'preact/debug/dist/debug.umd.js' {
  declare module.exports: $Exports<'preact/debug/dist/debug.umd'>;
}
declare module 'preact/debug/src/check-props.js' {
  declare module.exports: $Exports<'preact/debug/src/check-props'>;
}
declare module 'preact/debug/src/component-stack.js' {
  declare module.exports: $Exports<'preact/debug/src/component-stack'>;
}
declare module 'preact/debug/src/constants.js' {
  declare module.exports: $Exports<'preact/debug/src/constants'>;
}
declare module 'preact/debug/src/debug.js' {
  declare module.exports: $Exports<'preact/debug/src/debug'>;
}
declare module 'preact/debug/src/index' {
  declare module.exports: $Exports<'preact/debug/src'>;
}
declare module 'preact/debug/src/index.js' {
  declare module.exports: $Exports<'preact/debug/src'>;
}
declare module 'preact/devtools/dist/devtools.js' {
  declare module.exports: $Exports<'preact/devtools/dist/devtools'>;
}
declare module 'preact/devtools/dist/devtools.module.js' {
  declare module.exports: $Exports<'preact/devtools/dist/devtools.module'>;
}
declare module 'preact/devtools/dist/devtools.umd.js' {
  declare module.exports: $Exports<'preact/devtools/dist/devtools.umd'>;
}
declare module 'preact/devtools/src/devtools.js' {
  declare module.exports: $Exports<'preact/devtools/src/devtools'>;
}
declare module 'preact/devtools/src/index' {
  declare module.exports: $Exports<'preact/devtools/src'>;
}
declare module 'preact/devtools/src/index.js' {
  declare module.exports: $Exports<'preact/devtools/src'>;
}
declare module 'preact/dist/preact.js' {
  declare module.exports: $Exports<'preact/dist/preact'>;
}
declare module 'preact/dist/preact.min.js' {
  declare module.exports: $Exports<'preact/dist/preact.min'>;
}
declare module 'preact/dist/preact.module.js' {
  declare module.exports: $Exports<'preact/dist/preact.module'>;
}
declare module 'preact/dist/preact.umd.js' {
  declare module.exports: $Exports<'preact/dist/preact.umd'>;
}
declare module 'preact/hooks/dist/hooks.js' {
  declare module.exports: $Exports<'preact/hooks/dist/hooks'>;
}
declare module 'preact/hooks/dist/hooks.module.js' {
  declare module.exports: $Exports<'preact/hooks/dist/hooks.module'>;
}
declare module 'preact/hooks/dist/hooks.umd.js' {
  declare module.exports: $Exports<'preact/hooks/dist/hooks.umd'>;
}
declare module 'preact/hooks/src/index' {
  declare module.exports: $Exports<'preact/hooks/src'>;
}
declare module 'preact/hooks/src/index.js' {
  declare module.exports: $Exports<'preact/hooks/src'>;
}
declare module 'preact/src/clone-element.js' {
  declare module.exports: $Exports<'preact/src/clone-element'>;
}
declare module 'preact/src/component.js' {
  declare module.exports: $Exports<'preact/src/component'>;
}
declare module 'preact/src/constants.js' {
  declare module.exports: $Exports<'preact/src/constants'>;
}
declare module 'preact/src/create-context.js' {
  declare module.exports: $Exports<'preact/src/create-context'>;
}
declare module 'preact/src/create-element.js' {
  declare module.exports: $Exports<'preact/src/create-element'>;
}
declare module 'preact/src/diff/catch-error.js' {
  declare module.exports: $Exports<'preact/src/diff/catch-error'>;
}
declare module 'preact/src/diff/children.js' {
  declare module.exports: $Exports<'preact/src/diff/children'>;
}
declare module 'preact/src/diff/index' {
  declare module.exports: $Exports<'preact/src/diff'>;
}
declare module 'preact/src/diff/index.js' {
  declare module.exports: $Exports<'preact/src/diff'>;
}
declare module 'preact/src/diff/props.js' {
  declare module.exports: $Exports<'preact/src/diff/props'>;
}
declare module 'preact/src/index' {
  declare module.exports: $Exports<'preact/src'>;
}
declare module 'preact/src/index.js' {
  declare module.exports: $Exports<'preact/src'>;
}
declare module 'preact/src/options.js' {
  declare module.exports: $Exports<'preact/src/options'>;
}
declare module 'preact/src/render.js' {
  declare module.exports: $Exports<'preact/src/render'>;
}
declare module 'preact/src/util.js' {
  declare module.exports: $Exports<'preact/src/util'>;
}
declare module 'preact/test-utils/dist/testUtils.js' {
  declare module.exports: $Exports<'preact/test-utils/dist/testUtils'>;
}
declare module 'preact/test-utils/dist/testUtils.module.js' {
  declare module.exports: $Exports<'preact/test-utils/dist/testUtils.module'>;
}
declare module 'preact/test-utils/dist/testUtils.umd.js' {
  declare module.exports: $Exports<'preact/test-utils/dist/testUtils.umd'>;
}
declare module 'preact/test-utils/src/index' {
  declare module.exports: $Exports<'preact/test-utils/src'>;
}
declare module 'preact/test-utils/src/index.js' {
  declare module.exports: $Exports<'preact/test-utils/src'>;
}
