// flow-typed signature: e2066b690e43506e093fc7579a9033fd
// flow-typed version: <<STUB>>/preact-render-to-string_v^5.1.9/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'preact-render-to-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'preact-render-to-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'preact-render-to-string/dist' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/dist/index.module' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/dist/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/dist/jsx.modern' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/dist/jsx.module' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/jsx' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/polyfills' {
  declare module.exports: any;
}

declare module 'preact-render-to-string/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'preact-render-to-string/dist/index' {
  declare module.exports: $Exports<'preact-render-to-string/dist'>;
}
declare module 'preact-render-to-string/dist/index.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist'>;
}
declare module 'preact-render-to-string/dist/index.module.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/index.module'>;
}
declare module 'preact-render-to-string/dist/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/jsx'>;
}
declare module 'preact-render-to-string/dist/jsx.modern.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/jsx.modern'>;
}
declare module 'preact-render-to-string/dist/jsx.module.js' {
  declare module.exports: $Exports<'preact-render-to-string/dist/jsx.module'>;
}
declare module 'preact-render-to-string/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/jsx'>;
}
declare module 'preact-render-to-string/src/index' {
  declare module.exports: $Exports<'preact-render-to-string/src'>;
}
declare module 'preact-render-to-string/src/index.js' {
  declare module.exports: $Exports<'preact-render-to-string/src'>;
}
declare module 'preact-render-to-string/src/jsx.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/jsx'>;
}
declare module 'preact-render-to-string/src/polyfills.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/polyfills'>;
}
declare module 'preact-render-to-string/src/util.js' {
  declare module.exports: $Exports<'preact-render-to-string/src/util'>;
}
