// flow-typed signature: bb64bdb2fea45ad369331b6c44b39fe1
// flow-typed version: <<STUB>>/rollup-plugin-node-polyfills_v^0.2.1/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-node-polyfills'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-node-polyfills' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-node-polyfills/dist' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/assert' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/browserify-fs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/buffer-es6' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/console' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/constants' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/crypto-browserify' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/domain' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/empty' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/events' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/global' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/http-lib/capability' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/http-lib/request' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/http-lib/response' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/http-lib/to-arraybuffer' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/http' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/inherits' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/os' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/path' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/process-es6' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/punycode' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/qs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/buffer-list' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/duplex' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/passthrough' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/readable' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/transform' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/writable' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/setimmediate' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/stream' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/string-decoder' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/timers' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/tty' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/url' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/util' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/vm' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/adler32' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/binding' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/crc32' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/deflate' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/inffast' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/inflate' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/inftrees' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/messages' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/trees' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/utils' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/zstream' {
  declare module.exports: any;
}

declare module 'rollup-plugin-node-polyfills/polyfills/zlib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-node-polyfills/dist/index' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/dist'>;
}
declare module 'rollup-plugin-node-polyfills/dist/index.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/dist'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/assert.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/assert'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/browserify-fs.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/browserify-fs'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/buffer-es6.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/buffer-es6'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/console.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/console'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/constants.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/constants'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/crypto-browserify.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/crypto-browserify'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/domain.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/domain'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/empty.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/empty'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/events.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/events'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/global.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/global'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/http-lib/capability.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/http-lib/capability'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/http-lib/request.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/http-lib/request'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/http-lib/response.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/http-lib/response'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/http-lib/to-arraybuffer.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/http-lib/to-arraybuffer'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/http.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/http'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/inherits.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/inherits'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/os.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/os'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/path.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/path'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/process-es6.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/process-es6'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/punycode.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/punycode'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/qs.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/qs'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/buffer-list.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/readable-stream/buffer-list'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/duplex.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/readable-stream/duplex'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/passthrough.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/readable-stream/passthrough'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/readable.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/readable-stream/readable'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/transform.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/readable-stream/transform'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/readable-stream/writable.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/readable-stream/writable'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/setimmediate.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/setimmediate'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/stream.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/stream'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/string-decoder.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/string-decoder'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/timers.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/timers'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/tty.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/tty'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/url.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/url'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/util.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/util'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/vm.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/vm'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/adler32.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/adler32'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/binding.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/binding'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/crc32.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/crc32'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/deflate.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/deflate'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/inffast.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/inffast'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/inflate.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/inflate'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/inftrees.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/inftrees'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/messages.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/messages'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/trees.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/trees'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/utils.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/utils'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib-lib/zstream.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib-lib/zstream'>;
}
declare module 'rollup-plugin-node-polyfills/polyfills/zlib.js' {
  declare module.exports: $Exports<'rollup-plugin-node-polyfills/polyfills/zlib'>;
}
