// flow-typed signature: b3735c05ec51fa680961b25d632dbed2
// flow-typed version: <<STUB>>/simplestyle-js_v^2.3.0-beta.0/flow_v0.156.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simplestyle-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simplestyle-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'simplestyle-js/dist' {
  declare module.exports: any;
}

declare module 'simplestyle-js/dist/simplestyle-js.cjs.development' {
  declare module.exports: any;
}

declare module 'simplestyle-js/dist/simplestyle-js.cjs.production.min' {
  declare module.exports: any;
}

declare module 'simplestyle-js/dist/simplestyle-js.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'simplestyle-js/dist/index' {
  declare module.exports: $Exports<'simplestyle-js/dist'>;
}
declare module 'simplestyle-js/dist/index.js' {
  declare module.exports: $Exports<'simplestyle-js/dist'>;
}
declare module 'simplestyle-js/dist/simplestyle-js.cjs.development.js' {
  declare module.exports: $Exports<'simplestyle-js/dist/simplestyle-js.cjs.development'>;
}
declare module 'simplestyle-js/dist/simplestyle-js.cjs.production.min.js' {
  declare module.exports: $Exports<'simplestyle-js/dist/simplestyle-js.cjs.production.min'>;
}
declare module 'simplestyle-js/dist/simplestyle-js.esm.js' {
  declare module.exports: $Exports<'simplestyle-js/dist/simplestyle-js.esm'>;
}
