// flow-typed signature: 52ee996274be0a472763cf5d1bff6cfc
// flow-typed version: <<STUB>>/snowpack_v^3.8.2/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snowpack'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snowpack' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snowpack/assets/hmr-client' {
  declare module.exports: any;
}

declare module 'snowpack/assets/hmr-error-overlay' {
  declare module.exports: any;
}

declare module 'snowpack/assets/require-or-import' {
  declare module.exports: any;
}

declare module 'snowpack/assets/snowpack-init-file' {
  declare module.exports: any;
}

declare module 'snowpack/index.bin' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/build-import-proxy' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/build-pipeline' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/file-builder' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/file-urls' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/import-css' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/import-resolver' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/import-sri' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/optimize' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/build/process' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/commands/add-rm' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/commands/build' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/commands/dev' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/commands/init' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/commands/paint' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/commands/prepare' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/config' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/dev/hmr' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/hmr-server-engine' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/lexer-util' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/logger' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/plugins/plugin-esbuild' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/rewrite-imports' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/scan-import-glob' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/scan-imports' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/sources/local-install' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/sources/local' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/sources/remote' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/sources/util' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/ssr-loader' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/ssr-loader/sourcemaps' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/ssr-loader/transform' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/types' {
  declare module.exports: any;
}

declare module 'snowpack/lib/cjs/util' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/build-import-proxy' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/build-pipeline' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/file-builder' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/file-urls' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/import-css' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/import-resolver' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/import-sri' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/optimize' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/build/process' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/commands/add-rm' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/commands/build' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/commands/dev' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/commands/init' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/commands/paint' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/commands/prepare' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/config' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/dev/hmr' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/hmr-server-engine' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/lexer-util' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/logger' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/plugins/plugin-esbuild' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/rewrite-imports' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/scan-import-glob' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/scan-imports' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/sources/local-install' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/sources/local' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/sources/remote' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/sources/util' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/ssr-loader' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/ssr-loader/sourcemaps' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/ssr-loader/transform' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/types' {
  declare module.exports: any;
}

declare module 'snowpack/lib/esm/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snowpack/assets/hmr-client.js' {
  declare module.exports: $Exports<'snowpack/assets/hmr-client'>;
}
declare module 'snowpack/assets/hmr-error-overlay.js' {
  declare module.exports: $Exports<'snowpack/assets/hmr-error-overlay'>;
}
declare module 'snowpack/assets/require-or-import.js' {
  declare module.exports: $Exports<'snowpack/assets/require-or-import'>;
}
declare module 'snowpack/assets/snowpack-init-file.js' {
  declare module.exports: $Exports<'snowpack/assets/snowpack-init-file'>;
}
declare module 'snowpack/index.bin.js' {
  declare module.exports: $Exports<'snowpack/index.bin'>;
}
declare module 'snowpack/lib/cjs/build/build-import-proxy.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/build-import-proxy'>;
}
declare module 'snowpack/lib/cjs/build/build-pipeline.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/build-pipeline'>;
}
declare module 'snowpack/lib/cjs/build/file-builder.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/file-builder'>;
}
declare module 'snowpack/lib/cjs/build/file-urls.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/file-urls'>;
}
declare module 'snowpack/lib/cjs/build/import-css.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/import-css'>;
}
declare module 'snowpack/lib/cjs/build/import-resolver.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/import-resolver'>;
}
declare module 'snowpack/lib/cjs/build/import-sri.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/import-sri'>;
}
declare module 'snowpack/lib/cjs/build/optimize.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/optimize'>;
}
declare module 'snowpack/lib/cjs/build/process.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/build/process'>;
}
declare module 'snowpack/lib/cjs/commands/add-rm.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/commands/add-rm'>;
}
declare module 'snowpack/lib/cjs/commands/build.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/commands/build'>;
}
declare module 'snowpack/lib/cjs/commands/dev.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/commands/dev'>;
}
declare module 'snowpack/lib/cjs/commands/init.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/commands/init'>;
}
declare module 'snowpack/lib/cjs/commands/paint.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/commands/paint'>;
}
declare module 'snowpack/lib/cjs/commands/prepare.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/commands/prepare'>;
}
declare module 'snowpack/lib/cjs/config.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/config'>;
}
declare module 'snowpack/lib/cjs/dev/hmr.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/dev/hmr'>;
}
declare module 'snowpack/lib/cjs/hmr-server-engine.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/hmr-server-engine'>;
}
declare module 'snowpack/lib/cjs/index' {
  declare module.exports: $Exports<'snowpack/lib/cjs'>;
}
declare module 'snowpack/lib/cjs/index.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs'>;
}
declare module 'snowpack/lib/cjs/lexer-util.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/lexer-util'>;
}
declare module 'snowpack/lib/cjs/logger.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/logger'>;
}
declare module 'snowpack/lib/cjs/plugins/plugin-esbuild.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/plugins/plugin-esbuild'>;
}
declare module 'snowpack/lib/cjs/rewrite-imports.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/rewrite-imports'>;
}
declare module 'snowpack/lib/cjs/scan-import-glob.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/scan-import-glob'>;
}
declare module 'snowpack/lib/cjs/scan-imports.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/scan-imports'>;
}
declare module 'snowpack/lib/cjs/sources/local-install.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/sources/local-install'>;
}
declare module 'snowpack/lib/cjs/sources/local.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/sources/local'>;
}
declare module 'snowpack/lib/cjs/sources/remote.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/sources/remote'>;
}
declare module 'snowpack/lib/cjs/sources/util.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/sources/util'>;
}
declare module 'snowpack/lib/cjs/ssr-loader/index' {
  declare module.exports: $Exports<'snowpack/lib/cjs/ssr-loader'>;
}
declare module 'snowpack/lib/cjs/ssr-loader/index.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/ssr-loader'>;
}
declare module 'snowpack/lib/cjs/ssr-loader/sourcemaps.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/ssr-loader/sourcemaps'>;
}
declare module 'snowpack/lib/cjs/ssr-loader/transform.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/ssr-loader/transform'>;
}
declare module 'snowpack/lib/cjs/types.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/types'>;
}
declare module 'snowpack/lib/cjs/util.js' {
  declare module.exports: $Exports<'snowpack/lib/cjs/util'>;
}
declare module 'snowpack/lib/esm/build/build-import-proxy.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/build-import-proxy'>;
}
declare module 'snowpack/lib/esm/build/build-pipeline.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/build-pipeline'>;
}
declare module 'snowpack/lib/esm/build/file-builder.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/file-builder'>;
}
declare module 'snowpack/lib/esm/build/file-urls.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/file-urls'>;
}
declare module 'snowpack/lib/esm/build/import-css.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/import-css'>;
}
declare module 'snowpack/lib/esm/build/import-resolver.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/import-resolver'>;
}
declare module 'snowpack/lib/esm/build/import-sri.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/import-sri'>;
}
declare module 'snowpack/lib/esm/build/optimize.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/optimize'>;
}
declare module 'snowpack/lib/esm/build/process.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/build/process'>;
}
declare module 'snowpack/lib/esm/commands/add-rm.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/commands/add-rm'>;
}
declare module 'snowpack/lib/esm/commands/build.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/commands/build'>;
}
declare module 'snowpack/lib/esm/commands/dev.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/commands/dev'>;
}
declare module 'snowpack/lib/esm/commands/init.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/commands/init'>;
}
declare module 'snowpack/lib/esm/commands/paint.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/commands/paint'>;
}
declare module 'snowpack/lib/esm/commands/prepare.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/commands/prepare'>;
}
declare module 'snowpack/lib/esm/config.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/config'>;
}
declare module 'snowpack/lib/esm/dev/hmr.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/dev/hmr'>;
}
declare module 'snowpack/lib/esm/hmr-server-engine.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/hmr-server-engine'>;
}
declare module 'snowpack/lib/esm/index' {
  declare module.exports: $Exports<'snowpack/lib/esm'>;
}
declare module 'snowpack/lib/esm/index.js' {
  declare module.exports: $Exports<'snowpack/lib/esm'>;
}
declare module 'snowpack/lib/esm/lexer-util.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/lexer-util'>;
}
declare module 'snowpack/lib/esm/logger.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/logger'>;
}
declare module 'snowpack/lib/esm/plugins/plugin-esbuild.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/plugins/plugin-esbuild'>;
}
declare module 'snowpack/lib/esm/rewrite-imports.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/rewrite-imports'>;
}
declare module 'snowpack/lib/esm/scan-import-glob.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/scan-import-glob'>;
}
declare module 'snowpack/lib/esm/scan-imports.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/scan-imports'>;
}
declare module 'snowpack/lib/esm/sources/local-install.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/sources/local-install'>;
}
declare module 'snowpack/lib/esm/sources/local.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/sources/local'>;
}
declare module 'snowpack/lib/esm/sources/remote.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/sources/remote'>;
}
declare module 'snowpack/lib/esm/sources/util.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/sources/util'>;
}
declare module 'snowpack/lib/esm/ssr-loader/index' {
  declare module.exports: $Exports<'snowpack/lib/esm/ssr-loader'>;
}
declare module 'snowpack/lib/esm/ssr-loader/index.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/ssr-loader'>;
}
declare module 'snowpack/lib/esm/ssr-loader/sourcemaps.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/ssr-loader/sourcemaps'>;
}
declare module 'snowpack/lib/esm/ssr-loader/transform.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/ssr-loader/transform'>;
}
declare module 'snowpack/lib/esm/types.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/types'>;
}
declare module 'snowpack/lib/esm/util.js' {
  declare module.exports: $Exports<'snowpack/lib/esm/util'>;
}
