// flow-typed signature: 669657e9131045bf8c2cfa01cfa8c688
// flow-typed version: <<STUB>>/@snowpack/app-scripts-preact_v^1.4.0/flow_v0.123.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@snowpack/app-scripts-preact'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@snowpack/app-scripts-preact' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@snowpack/app-scripts-preact/jest.config' {
  declare module.exports: any;
}

declare module '@snowpack/app-scripts-preact/jest/babelTransform' {
  declare module.exports: any;
}

declare module '@snowpack/app-scripts-preact/jest/cssTransform' {
  declare module.exports: any;
}

declare module '@snowpack/app-scripts-preact/jest/fileTransform' {
  declare module.exports: any;
}

declare module '@snowpack/app-scripts-preact/snowpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@snowpack/app-scripts-preact/jest.config.js' {
  declare module.exports: $Exports<'@snowpack/app-scripts-preact/jest.config'>;
}
declare module '@snowpack/app-scripts-preact/jest/babelTransform.js' {
  declare module.exports: $Exports<'@snowpack/app-scripts-preact/jest/babelTransform'>;
}
declare module '@snowpack/app-scripts-preact/jest/cssTransform.js' {
  declare module.exports: $Exports<'@snowpack/app-scripts-preact/jest/cssTransform'>;
}
declare module '@snowpack/app-scripts-preact/jest/fileTransform.js' {
  declare module.exports: $Exports<'@snowpack/app-scripts-preact/jest/fileTransform'>;
}
declare module '@snowpack/app-scripts-preact/snowpack.config.js' {
  declare module.exports: $Exports<'@snowpack/app-scripts-preact/snowpack.config'>;
}
